name: Eda SUTUNC
author: Eda Sutunc
baseurl: ""
description: "interdisciplinary artist"
twitter: http://www.twitter.com/
behance: https://www.behance.net/esutunc
facebook: http://www.facebook.com
email: rnpatel[at]me.com
location: 42°2'16"N   70°12'47"W

markdown: kramdown

permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
